class LocatorLoginPage:
    sign_out_classname = "logout"
    search_textbox_id = "search_query_top"
    search_button_name = "submit_search"
    women_tab_xpath = "//a[@class='sf-with-ul'][contains(text(),'Women')]"
    dresses_tab_xpath = "//a[@class='sf-with-ul'][contains(text(),'Dresses')]"
    tshirt_tab_xpath = "//body[@id='my-account']/div[@id='page']/div[@class='header-container']/header[@id='header']/div/div[@class='container']/div[@class='row']/div[@id='block_top_menu']/ul[@class='sf-menu clearfix menu-content sf-js-enabled sf-arrows']/li[3]/a[1]"
    order_history_tab_xpath = "//i[@class='icon-list-ol']"
    my_credit_slip_xpath = "//i[@class='icon-ban-circle']"
    my_address_xpath = "//i[@class='icon-building']"
    my_personal_info_xpath = "//i[@class='icon-user']"
    my_wishlist_xpath = "//li[@class='lnk_wishlist']//a"
